[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "med_im"
version = "1.0.0"
description = "Medical Imaging Coursework"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "scikit-image",
    "matplotlib",
    "pydicom",     
    "torch",
    "torchvision",
]

[tool.setuptools]
packages = ["med_im"]

[project.optional-dependencies]
dev = [
    "pytest",
    "sphinx",
    "jupyter"
]

[tool.pytest.ini_options]
testpaths = ["tests"]